### ISSUE TITLE
Steam login button disappeared

### ISSUE THREAD

**Issue by jffz** [defaye/discourse-steam-login#5]
I've been using this plugin for my fresh Discourse install and worked like a charm but seems like the Steam login button disappeared since yesterday on my discourse install. Noway to login with a steam account.

The only modificaitons I've made are disabling local users login (which i re-enabled justin case) and enabling twitter login.

Here is a part of my app.yml file:

`hooks:
after_code:
- exec:
cd: $home/plugins
cmd:
- git clone https://github.com/discourse/docker_manager.git
- git clone https://github.com/defaye/discourse-steam-login.git
- git clone https://github.com/discourse/discourse-solved.git
- git clone https://github.com/discourse/discourse-staff-notes.git
- git clone https://github.com/discourse/twitter-profile-link.git`

forum link in cse it could help : https://forum.hsfactory.net

**Comment by defaye** [comment]
Unless you have made an effort to narrow down whether it is a problem with the plugin I don't have time to look at this. You need to debug the application, that is not my job. Remove other plugins besides those that come as standard and use the latest release. I have no problems with my installation. If you continue to have problems, please come back with a better report.

**Comment by jffz** [comment]
Hmmm .. I already triied to remove all other plugins.
Also triied to quote my STEAM_WEB_API_KEY.
Triied rebuild (in first shot).

What i can add to report ? Maybe my discourse version, i triied everything that i can ...

Version	v1.6.0.beta4 +62

**Comment by jffz** [comment]
Seems working this time, i will investigate, maybe are you interested to know which can cause issues ?

Sorry for disturbing.

**Comment by defaye** [comment]
By all means. What was the problem?

**Comment by jffz** [comment]
The steam login features just disappeared like it was not installed.

Seems to due to this plugin::
https://github.com/crob611/discourse-image-gallery.git
