### ISSUE TITLE
Accessing a user's Steam ID

### ISSUE THREAD

**Issue by sean-clayton** [defaye/discourse-steam-login#7]
Is there a way an admin can access a user's unique Steam ID when viewing their profile in the admin panel? I see in the code that you're storing it—I'm not entirely sure how to get access to it (total Ruby/RoR noob, sorry 😢 )

And maybe have Steam show up in the "Logins" section?

![image](https://cloud.githubusercontent.com/assets/1108160/16919231/de14912a-4cd6-11e6-993d-da569d56a9c3.png)

Thank you for the plugin—it's helped me out immensely! I wouldn't mind helping out fleshing the project out, I just lack the Ruby chops, but I'd be willing to learn.

**Edit:**

D'oh, I just saw your experimental branch! I'll close this issue and try that out whenever I can. Thanks, again!

**Comment by defaye** [comment]
Have a look at this https://meta.discourse.org/t/linkedin-oauth2-plugin/46818/8

**Comment by sean-clayton** [comment]
I saw that today and updated my instance to latest Master in hopes that it'd show up, but no dice (Which sort of led me to create this issue). I only assume this is because Steam uses OpenID and not OAuth. What's odd to me (now that I've looked at the code) is that [OpenID providers apparently already have configuration to show up here](https://github.com/cpradio/discourse/blob/master/app/models/user.rb#L766)?

**Comment by defaye** [comment]
If you're comfortable with making a change to discourse yourself there's nothing stopping you from implementing the same patch proposed by cpradio. As for what this plugin uses for authentication, it was depending on https://github.com/reu/omniauth-steam. But I had to patch his code myself to get it to work properly as the Rubygems version was out of sync with the Github one (or something like that). Now I just have my own hard-copy to avoid any drama. And that's OAuth 1.

**Comment by Technoblazed** [comment]
@sean-clayton Did you ever manage to figure this out?
